local builder = require("ntf.assert.builder")

describe("ntf.assert.builder", function()
  local function fails(fn)
    local ok = pcall(fn)
    return not ok
  end

  it("supports equal / same", function()
    assert.equal(1, 1)
    assert.same({ a = 1, b = { 2 } }, { a = 1, b = { 2 } })
    assert.is_true(fails(function()
      assert.equal(1, 2)
    end))
    assert.is_true(fails(function()
      assert.same({ 1 }, { 2 })
    end))
  end)

  it("supports is_true / is_false / is_nil / truthy / falsy", function()
    assert.is_true(true)
    assert.is_false(false)
    assert.is_nil(nil)
    assert.truthy(1)
    assert.falsy(nil)
    assert.is_true(fails(function()
      assert.is_true(false)
    end))
  end)

  it("supports match", function()
    assert.match("b.d", "abcd")
    assert.is_true(fails(function()
      assert.match("zzz", "abcd")
    end))
  end)

  it("supports the `no` negation modifier", function()
    assert.no.equal(1, 2)
    assert.no.is_nil(1)
    assert.is_true(fails(function()
      assert.no.equal(1, 1)
    end))
  end)

  it("callable form behaves like the builtin assert", function()
    assert(true)
    assert.is_true(fails(function()
      assert(false, "boom")
    end))
  end)

  it("can register a custom assertion via :register", function()
    local a = builder.new()
    require("ntf.assert.message"):set("custom.positive", "should be even")
    require("ntf.assert.message"):set("custom.negative", "should not be even")
    a:register("assertion", "even", function(_, args)
      return args[1] % 2 == 0
    end, "custom.positive", "custom.negative")
    a.even(2)
    assert.is_true(not pcall(function()
      a.even(3)
    end))
  end)

  it("registers custom asserts through ntf.assert (assertlib path)", function()
    -- the surface per-plugin helpers use: asserts.create(name):register_eq(fn)
    require("ntf.assert").asserts.create("spec_double"):register_eq(function(n)
      return n * 2
    end)
    assert.spec_double(3, 6)
    assert.no.spec_double(3, 7)
    assert.is_true(fails(function()
      assert.spec_double(3, 7)
    end))
  end)
end)
